name: flutter_google_ad_manager
description: Flutter plugin for Google Ad Manager(DoubleClick for Publishers).
version: 0.11.0
homepage: https://github.com/ko2ic/flutter_google_ad_manager

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ^1.10.0
  
dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ko2ic.fluttergoogleadmanager
        pluginClass: FlutterGoogleAdManagerPlugin
      ios:
        pluginClass: FlutterGoogleAdManagerPlugin